### ISSUE TITLE
Interactive prompt

### ISSUE THREAD

**Issue by droctothorpe** [stern/stern#120]
I forked and extended stern to include a `--prompt / -p` flag to surface an interactive prompt that looks up values associated with the `app.kubernetes.io/instance` key and lets you select from those options to consume all of the logs associated with a specified Helm chart / ArgoCD application. It's quite useful and could be a good candidate for an upstream contribution. Would you be interested in a PR like that? The work is more or less done so it would be easy to contribute. 

Here's an example of usage (disregard the fact that it's called spoke):
![image](https://camo.githubusercontent.com/e605710344e6ea054216e6adbaf4d2442a6b7bb567e93f1988f1f3b6e5fd6b20/68747470733a2f2f692e696d6775722e636f6d2f4f446b347247622e676966)

**Comment by superbrothers** [comment]
It looks nice! 

@floryut WDYT?

**Comment by floryut** [comment]
> It looks nice!
> 
> @floryut WDYT?

That could be indeed added, as you already do all the work! 😄

**Comment by droctothorpe** [comment]
Great! I'll aim to submit a PR on Friday.

**Comment by droctothorpe** [comment]
Thanks for the encouragement! Apologies for the delay. I had to jump through some hoops on my work computer to make an open source contribution. 

Here's a link to the PR: https://github.com/stern/stern/pull/128

**Comment by droctothorpe** [comment]
PR merged.
