### ISSUE TITLE
Add an option for verbose logging

### ISSUE THREAD

**Issue by emilhem** [stern/stern#139]
It would be useful if we had an cli option to log verbosely stern's functionality. I suggest `--verbose`

Example would be to see some of the data that stern is working with when performing certain actions.

### Discussed in https://github.com/stern/stern/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **emilhem** July  1, 2021</sup>
I'm trying to fault trace why the stern command isn't doing expected stuff. Is there a way to turn on verbose logging?

I've tried `--verbose` and `-V`.

Use case:
The issue I'm trying to investigate is receiving `Error: No matching labels`. </div>

**Comment by mailsanchu** [comment]
I am not getting any response from serve. Any option to enable verbose logging?

**Comment by mailsanchu** [comment]
Seeing this error but kubectl is working fine 
`the server was unable to return a response in the time allotted, but may still be processing the request (get pods)`

**Comment by mailsanchu** [comment]
```
 kubectl version --short
Client Version: v1.20.15-eks-fb459a0
Server Version: v1.21.14-eks-fb459a0

```
