### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#14]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/71, but it was originally created by [wookasz](https://github.com/wookasz)...

This tool is incredibly useful, but based on the age of some issues and pull requests it seems it may no longer be maintained?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [markxnelson](https://github.com/markxnelson)...

Hi Lukasz, yes we will still maintain this. We are working through many of the old repos and working out which ones are still used.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [cknowles](https://github.com/cknowles)...

@markxnelson that's good news! Do you know the normal ETA to add someone to the [OCA](https://www.oracle.com/technetwork/community/oca-486395.html)? My boss emailed sign off for our company over a month ago and we're not on the list yet.

We'd love to get https://github.com/wercker/stern/pull/67, if not soon we'll likely fork and publish this ourselves.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [markxnelson](https://github.com/markxnelson)...

HI @c-knowles sorry to hear that, OCA is usually updated within 24 hours.  Can you forward me your email and I will check on it for you. mark.x.nelson@oracle.com

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [cknowles](https://github.com/cknowles)...

@markxnelson no problem, our concern was mainly keeping the project going. Thanks for the feedback, will get onto that shortly.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [markxnelson](https://github.com/markxnelson)...

Sure, we're still maintaining it. We are still working through about 300 repos and working out which ones are still important. And we are putting a lot of our resource into the core code base. Thanks for bumping.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [markxnelson](https://github.com/markxnelson)...

@c-knowles your OCA was processed now.  So we can merge any PRs from you.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [manishbansal8843](https://github.com/manishbansal8843)...

@markxnelson Is team still maintaining this project?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [cknowles](https://github.com/cknowles)...

@markxnelson can we do a release with https://github.com/wercker/stern/pull/67 in it?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [markxnelson](https://github.com/markxnelson)...

Hi, I am no longer a maintainer.  @hatchan can you please respond?

**Comment by floryut** [comment]
This one is not relevant anymore
/close
