### ISSUE TITLE
Automatically match all pods in a given namespace

### ISSUE THREAD

**Issue by vsimon** [stern/stern#141]
**What would you like to be added**:

I would like to suggest a DX improvement for running with only the namespace argument specified. It would automatically match all pods in the given namespace.

The goal would be to run a command:

```
stern -n test-env-with-multiple-charts
```

and tail all the pods and containers running in that namespace.

**Why is this needed**:

If a developer has the entire environment in a namespace with various charts installed, It would take less cognitive load to tail logs with a single argument:

```
stern -n test-env-with-multiple-charts
```

instead of

```
stern -n test-env-with-multiple-charts -l app=redis -l app=mysql -l app=chart-foo
```

Even if there were a common label applied across all chart values, the knowledge of that common label would still be required:

```
stern -n test-env-with-multiple-charts -l common-label=foo
```

**Comment by superbrothers** [comment]
The following command will match all Pods in that namespace.

```
stern -n test-env-with-multiple-charts .
```

Is there a problem with this?

**Comment by vsimon** [comment]
The `.` is very good, thank you! I see it now in one of the exclude container examples in the README thanks!

**Comment by wg-d** [comment]
How are you doing? I hope you and your family are fine in this pandemic.
I have something(can be kind of easy job) for you. 
Of course it's related to both you and I.
I hope to contact with you on skype for convenience.
Here is my skype id:   live:.cid.a9f352144b198de9
Thanks in advance.
