### ISSUE TITLE
Feature request: print all available logs and exit

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#15]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/72, but it was originally created by [emptywee](https://github.com/emptywee)...

Hello.

Is it possible to add a flag to stern to stop tailing after all available logs are shown? Would be very useful when you need to print logs from multiple different pods (using a regexp or wildcard or label selector) and pipe them to grep. Currently it keeps tailing no matter what and you don't really know if stern has shown all recent logs or still printing, because grep is filtering that info out.

Thank you.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [hatchan](https://github.com/hatchan)...

Currently it is only possible to follow the logs, so it won't quite after it has shown the logs.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [olli-miettinen-arm](https://github.com/olli-miettinen-arm)...

This would be very nice feature, a stop switch that would allow using stern in scripts.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [henricook](https://github.com/henricook)...

We'd also love this, so we can tail multiple pods and then operate on the output (e.g. grep response times and then `| sort -n`)

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [fuhbar](https://github.com/fuhbar)...

Same here. We'd love to see this implemented very much like `tail(1)`.

Our use case is as follows: Using helm deployment hooks in CD pipelines leaves us with the task of feeding back the pod logs to the user respectively the CD system, so that the user is able to find information why her deployment has failed.  

Stern is the perfect answer for accomplishing this. :)

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [jacobstr](https://github.com/jacobstr)...

One nice way to accomplish this might be an `until` flag to complement `since`. e.g.

```
stern --until=$(date +%s)
```

Could print all logs until `now` and exit.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [ljohnston](https://github.com/ljohnston)...

IMO, a `--until` flag is the best way to implement this. Not only could you stop it at `now`, but you could go back and see what was happening during a specific time frame (e.g. `stern --since 4h --until 3h ...`).

**Comment by bigbits22** [comment]
any news on this?
