### ISSUE TITLE
Add an option for a "deployment-query"

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#159]
**What would you like to be added**:

> The default argument takes a "pod-query", can there be an option for a "deployment-query"? 😄
> 
> That way one could pass "app$" and have it match the app-756d764c46-njkvx pod without the longer "app-[0-9a-z]{10}-[0-9a-z]{5}" regex.
> 
> Agreed, the easiest way to do this is to use a label selector. Just so I can use this tool easier, I have add something extra. Someone will ask: "Why are you adding these labels?" The answer being "Because I want to use stern in an easier way".

- https://github.com/stern/stern/issues/158#issuecomment-922359537

**Why is this needed**:

cc/ @vsimon

**Comment by superbrothers** [comment]
I don't have a strong motivation to add this feature, since we can check the pod labels with `kubectl get po --show-labels`. Also, in many scenarios, pod-query gives the expected results.

```
$ kubectl create deploy app --image nginxinc/nginx-unprivileged
$ kubectl create deploy app-admin --image nginxinc/nginx-unprivileged
$ kubectl create deploy app-sdk --image nginxinc/nginx-unprivileged

$ kubectl get po --show-labels
NAME                        READY   STATUS    RESTARTS   AGE   LABELS
app-756d764c46-njkvx        1/1     Running   0          47h   app=app,pod-template-hash=756d764c46
app-admin-dc858d4d4-wmbh7   1/1     Running   0          47h   app=app-admin,pod-template-hash=dc858d4d4
app-sdk-55cbbb55-65tz4      1/1     Running   0          47h   app=app-sdk,pod-template-hash=55cbbb55

$ stern -l app=app
```

If we add a new feature, we can consider specifying the resource in the form `<resource>/<regexp>` as one idea.

```
$ stern "deployment/app$"
```

**Comment by vsimon** [comment]
For my user-defined helm charts, I can add `app=<app>` (I don't think helm adds them automatically "for free" when doing helm install...). I also use third party charts, some use a different labelling convention by default like, `app.kubernetes.io/name=<app>` or `app.kubernetes.io/component=<app>`, so I'd have to add labels `app=<app>` to those kinds of charts use stern in a more uniform way.

> If we add a new feature, we can consider specifying the resource in the form <resource>/<regexp> as one idea. `$ stern "deployment/app$"`

I like the idea, it resembles the structure of some kubectl commands like port-forwarding where the default resource is assumed to be pod but you can port-forward to other resources with the `<resource>/` style both the long and short resource names (for example service/svc) are supported i.e.

```
kubectl port-forward pod/mypodname ...
kubectl port-forward deployment/mydeploymentname ...
kubectl port-forward service/myservicename ...
kubectl port-forward deploy/mydeploymentname ...
kubectl port-forward svc/myservicename ...
```
