### ISSUE TITLE
Any way to hide pod name and/or deployment?

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#16]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/74, but it was originally created by [jmreicha](https://github.com/jmreicha)...

Is there any way to turn off extra metadata?  The pod + deployment + timestamps are taking up over half of the visible line.  Since I already know what I want to look at is it possible to turn either the pod name or deployment names off?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [hatchan](https://github.com/hatchan)...

Currently there is no way of doing that. But I've worked a bit on being able to use templates here: https://github.com/wercker/stern/tree/templates Let me know what you think, it will probably change a bit. Hopefully I'll find some time to work on it soon.

**Comment by ryancastle** [comment]
This is possible with `-oraw` or templates and the shell redirection. The template controls the line format and the dropping stderr removes the pod status messages.

```
❯ stern POD --template '{{.Message}}{{"\n"}}' 2>/dev/null
Hello Foo
Hello Bar
```
