### ISSUE TITLE
Logs not shown – `cannot parse "failed" as "2006"`

### ISSUE THREAD

**Issue by AndiDog** [stern/stern#161]
**What happened**:

```
unexpected error: parsing time "failed" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "failed" as "2006"
```

when following logs of a Job on k8s version `v1.19.13-eks-8df270`.

**What you expected to happen**:

Logs should be shown.

**How to reproduce it (as minimally and precisely as possible)**:

Don't have a reproducible example. I'm not even sure whether this could be in stern, or is some kubernetes code issue. The error definitely hints at some Go date formatting code, and I only saw the issues with `stern`. I was able to see the Job being created, and could tail its logs with `k9s`.

**Environment**:
- stern version (use `stern --version`): 1.20.1
- OS (e.g: `cat /etc/os-release`): macOS 11.5
- Install tools (e.g: Homebrew): homebrew
- Others: Tried these versions of kubectl in PATH (if it even matters) – v1.22.2 and v1.19.10

**Comment by superbrothers** [comment]
Can you tell me what flags you used `stern` with? (e.g. `stern --timestamps app`

**Comment by AndiDog** [comment]
```
stern -tn my-namespace --tail 0 .
```

**Comment by superbrothers** [comment]
Umm... I could not reproduce it.

```
$ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1

$ stern --version
version: 1.20.1
commit: a384d35f36e43953ac3c6af5a20ffc97cb8205cf
built at: 2021-09-11T12:17:12Z

$ k create deploy nginx --image nginxinc/nginx-unprivileged
deployment.apps/nginx created

$ k get po
NAME                     READY   STATUS    RESTARTS   AGE
nginx-66f6ffdddf-zr8qp   0/1     Pending   0          5s

$ stern -tn default --tail 1 .
+ nginx-66f6ffdddf-zr8qp › nginx-unprivileged
nginx-66f6ffdddf-zr8qp nginx-unprivileged 2021-10-02T10:40:03.889892565+09:00 2021/10/02 01:40:03 [notice] 1#1: start worker process 30
```

**Comment by AndiDog** [comment]
Definitely related to the `-t/--timestamps` option. The error does not appear if I leave that off.

(side note: I get `failed to create fsnotify watcher: too many open files` on macOS also without that option, and therefore cannot see all logs)

**Comment by odinnordico** [comment]
I can confirm the issue, i am using the api and when i set the `Timestamps: true` in the `Config` then i can see that error as well instead of the actual log message, when it is `false` the log is shown

**Comment by odinnordico** [comment]
Possible solution would be to warn [here](https://github.com/stern/stern/blob/cadf4399f174c04f81f002b5a79905971d2df6a3/stern/tail.go#L100) validating if `datetime` is not a date instead of breaking with the error, same behavior in [L94](https://github.com/stern/stern/blob/cadf4399f174c04f81f002b5a79905971d2df6a3/stern/tail.go#L94)
