### ISSUE TITLE
Documentation update and bug ?

### ISSUE THREAD

**Issue by jylenhofdecat** [stern/stern#163]
If I put "source <(stern completion=bash)" command just hang, but if I do "source <(stern --completion bash)" it is ok

**Comment by rkmathi** [comment]
@jylenhofdecat 
completion option must be used with `--` .

OK
```
$ stern --completion=bash
$ stern --completion bash
```

NG
```
$ stern completion=bash
```

**Comment by superbrothers** [comment]
@jylenhofdecat If you find a mistake in the documentation, please create a PR.
