### ISSUE TITLE
missing old log entry

### ISSUE THREAD

**Issue by DraconPern** [stern/stern#165]
So my log has one line.  The program wasn't able to load because missing libs so it should be stderr.  however the line isn't in the log.  here's the info.

```
draconpern@k8s-master:~$ k logs espresso-scp-0
./espresso_scp: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
draconpern@k8s-master:~$ ./stern espresso-scp
^C
draconpern@k8s-master:~$ ./stern --version
version: 1.20.1
commit: a384d35f36e43953ac3c6af5a20ffc97cb8205cf
built at: 2021-09-11T12:17:12Z
```

**Comment by superbrothers** [comment]
stern does not output logs older than 48 hours by default. Please try using `--since` option.

**Comment by DraconPern** [comment]
The entry was only a few minutes old.  I think it’s just that stern doesn’t capture some text for unknown reason.  I think it might be stderr that’s not getting captured.

**Comment by DraconPern** [comment]
Looking at past bugs, this is actually the same as #26 as the container has stopped. It looks like the normal logs command dumps log from stopped containers by default.  Would be nice if stern does the same.

**Comment by superbrothers** [comment]
I'll check it.

**Comment by superbrothers** [comment]
I'm sorry for the delay in replying. Yes, this is the same as #26, and pods that are already terminated are not targeted by default. Therefore, you need to specify `--container-state=terminated` as follows.

```
$ cat <<EOL | kubectl create -f-
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox
    command:
    - echo
    - hello
EOL
pod/app created

$ kubectl get po -o wide
NAME   READY   STATUS      RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
app    0/1     Completed   0          14s   10.244.0.2   kind-control-plane   <none>           <none>

$ stern app
^C

$ stern --container-state terminated app
+ app › app
app app hello
^C
```

Also, I do not intend to change the behavior of `--container-state` at this time.
