### ISSUE TITLE
Stern fails to work in multi-context setup

### ISSUE THREAD

**Issue by AayushPathak** [stern/stern#166]
**What happened**:
I added an additional kubeconfig file to my $KUBECONFIG variable to switch to a new context. Stern works perfectly with the old one but doesn't when switched to new context:
```
$ echo $KUBECONFIG
/home/aayush/.kube/config:/home/aayush/.kube/prod_config (new context)
```
```
$ stern test-api --all-namespaces --since 1m
E1101 18:55:44.776702    3973 retrywatcher.go:130] "Watch failed" err="unknown (get pods)"
E1101 18:55:45.083725    3973 retrywatcher.go:130] "Watch failed" err="unknown (get pods)"
E1101 18:55:46.192788    3973 retrywatcher.go:130] "Watch failed" err="unknown (get pods)"
```
I get the same result when adding the `--context` or `--kubeconfig` options.

`kubectl logs` is working perfectly with the new context and I have `watch` permission for `pods`
**What you expected to happen**:
Stern should have returned logs from the current context

**Environment**:
Rancher v2.4.11
```
$ stern --version
version: 1.20.1
commit: a384d35f36e43953ac3c6af5a20ffc97cb8205cf
built at: 2021-09-11T12:17:12Z
```

**Comment by superbrothers** [comment]
Does stern work correctly when run against a specific namespace?

If you use `--all-namespaces` flag, you will need to have permissions at cluster level. Therefore, make sure that you have permissions on Pods in `ClusterRole` and `ClusterRoleBinding`.

**Comment by AayushPathak** [comment]
@superbrothers you're right! I checked all the namespaces and turns out I don't have permissions for a few of them. Using the `--namespace` flag worked. Thanks!
