### ISSUE TITLE
MacOS ARM release

### ISSUE THREAD

**Issue by AverageMarcus** [stern/stern#174]
**What would you like to be added**:

It looks like the `master` branch has been updated to use the latest Go-releaser that supports building binaries for MacOS with the M1 chips. Would it be possible to get a new release generated so this binary is also built?

**Why is this needed**:

Unable to `kubectl krew install stern` on the new M1 Macs.

**Comment by superbrothers** [comment]
We will support `darwin/arm64` in the next release! It will be released in the coming days.

**Comment by AverageMarcus** [comment]
🎉  Fantastic! Thank you!

**Comment by superbrothers** [comment]
We released stern v1.21.0. It contains darwin/arm64 binary. Try it out 🍺

- https://github.com/stern/stern/releases/tag/v1.21.0
