### ISSUE TITLE
`stern --until pod-x=healthy`

### ISSUE THREAD

**Issue by felipecrs** [stern/stern#189]
**What would you like to be added**:

A flag, like `--until`, that would provide a way to exit `stern` given a condition.

**Why is this needed**:

It's really difficult to capture logs during installation of a Helm Chart during CI. Stern surely helps it, but comes with some additional challenges. Example: how do I make stern stop? An `--until` option would come in handy.

It could accept some conditions like if a given pod is healthy.

**Comment by superbrothers** [comment]
Since stern can target multiple Pods, this feature may not work well. For example, how about exiting stern when a Kubernetes object meets certain conditions?

```shell
kubectl create deploy nginx --image nginxinc/nginx-unprivileged
kubectl scale deploy nginx --replicas=3
stern nginx- &
STERN_PID="$!"
kubectl wait deployment nginx --for condition=Available=True --timeout=90s
kill "$STERN_PID"
```

**Comment by felipecrs** [comment]
I think that's enough. Thank you!
