### ISSUE TITLE
Command completions for fish shell

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#20]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/95, but it was originally created by [Lameorc](https://github.com/Lameorc)...

Hi, 
I'd really appreciate [fish shell](https://fishshell.com/) completions. This might be a bit more difficult than zsh/bash ones, since fish syntax is not compatible with them. Although from user point of view, the workflow would be very similiar eg:
```sh
stern --completion=fish > ~/.config/fish/completions/stern.fish
```

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [davinkevin](https://github.com/davinkevin)...

Very interested by this one ! It could be base on the completion system already existing for `kubectl` no?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [sters](https://github.com/sters)...

I'm using it. https://github.com/evanlucas/fish-kubectl-completions

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [kunickiaj](https://github.com/kunickiaj)...

Just tried the switch to fish yesterday and loving it so far. Threw this together to provide some completions for stern: https://github.com/kunickiaj/fish-completions-stern

PRs welcome, or if anyone wants to help incorporate it directly into `stern` that'd be awesome too!

**Comment by superbrothers** [comment]
I tried to work with `cmd.GenFishCompletion` in spf13/cobra v1.1.1, but it didn't seem to work. 🙃

**Comment by floryut** [comment]
> I tried to work with `cmd.GenFishCompletion` in spf13/cobra v1.1.1, but it didn't seem to work. 🙃

I used to work with Fish but that's a long time ago, not sure I can find anything useful :(
