### ISSUE TITLE
Support only tailing since stern starts

### ISSUE THREAD

**Issue by felipecrs** [stern/stern#200]
**What would you like to be added**:

Something like: `--since=now`, or perhaps `--since=0s` (which isn't currently supported).

**Why is this needed**:

I use stern in CI/CD, and I want to only show logs that appear AFTER I start stern.

Currently, the closest option is `--since=1s`.

**Comment by superbrothers** [comment]
You can use `stern --tail 0 <query>`.

```
$ stern -h | grep -- --tail
      --tail int                   The number of lines from the end of the logs to show. Defaults to -1, showing all logs. (default -1)
```

If you still have any issue, please feel free to reopen this issue.
