### ISSUE TITLE
Interleaved log output

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#21]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/96, but it was originally created by [sebastianvoss](https://github.com/sebastianvoss)...

When pods are emitting logs simultaneously the output is sometimes interleaved. This makes it very hard to read the output of stern. I'm using version `1.10.0` (k8s cluster AWS EKS version 2).

Sample output:
```
my-deployment-6854597977-8ffc6 my-app my-deployment-6854597977-bzmw9 23:25:41.614 [blaze-selector-0-3] INFO  org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /xxx:61213
my-app 23:25:41.614 [blaze-selector-0-0] INFO  org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /xxx:47462
```

Should be:
```
my-deployment-6854597977-8ffc6 my-app 23:25:41.614 [blaze-selector-0-3] INFO  org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /xxx:61213
my-deployment-6854597977-bzmw9 my-app 23:25:41.614 [blaze-selector-0-0] INFO  org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /xxx:47462
```

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [d11wtq](https://github.com/d11wtq)...

Guessing this should be solveable to pushing all the log output through a single go channel.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [henricook](https://github.com/henricook)...

I would love this, debugging historical issues on 3 pods is super hard when they're not interleaved, i end up writing each to a file and trying to scroll them all roughly in sync

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [gg7](https://github.com/gg7)...

In my experience, `export GOMAXPROCS=1` eliminates the race condition, unless stdout is blocked (e.g. when you do `Ctrl-]` in tmux). Hope this helps.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [jwthomp](https://github.com/jwthomp)...

> In my experience, `export GOMAXPROCS=1` eliminates the race condition, unless stdout is blocked (e.g. when you do `Ctrl-]` in tmux). Hope this helps.

Unfortunately not entirely in iTerm on a mac

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [mcary](https://github.com/mcary)...

Adding `--output raw` (even without GOMAXPROCS mentioned [above](https://github.com/wercker/stern/issues/96#issuecomment-468317232)) also seems to avoid the issue for me in OS X Terminal.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [knight42](https://github.com/knight42)...

For anyone who has encountered this problem, I have filed a PR #127 to fix it, you could try my patch.

**Comment by superbrothers** [comment]
This problem has probably already been fixed. If the problem still exists, please reopen the issue.

**Comment by jglick** [comment]
Still happening to me sometimes in 1.11.0.
