### ISSUE TITLE
Allow to specify `--exclude-pod` multiple times

### ISSUE THREAD

**Issue by felipecrs** [stern/stern#212]
**What would you like to be added**:

```
stern '.*' --exclude-pod pod-a --exclude-pod pod-b
```

So both gets excluded.

**Why is this needed**:

Currently the behavior is that only the last `--exclude-pod` specified is taken into account, the rest is ignored.

**Comment by tksm** [comment]
As you might already know, the value of the `--exclude-pod` flag is a regular expression so that you can exclude multiple pods like `--exclude-pod "pod-a|pod-b"` or `--exclude-pod "pod-[ab]"`.

>       --exclude-pod string         Pod name to exclude. (regular expression)

**Comment by felipecrs** [comment]
Thanks, that's what I use today, but I think it would be more intuitive if it accepted a list of strings.
