### ISSUE TITLE
Cannot find package "context" error, even after govendor sync

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#24]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/100, but it was originally created by [mirvpgh](https://github.com/mirvpgh)...

I'm still having trouble installing stern (on Xubuntu 16.04). I ran govendor sync in the stern directory, and it looked like it ran for several seconds. When I run go install (or go build), I get this error:
cmd/cli.go:18:2: cannot find package "context" in any of:
	/root/go/src/github.com/wercker/stern/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/root/go/src/context (from $GOPATH)

Any suggestions?

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [hatchan](https://github.com/hatchan)...

It looks like you are using a pretty old version of Go: 1.6. The package `context` was introduced to the Go in 1.7.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [mirvpgh](https://github.com/mirvpgh)...

Installed Go v1.7, and now I get this message when running the install:
\# github.com/wercker/stern/vendor/k8s.io/apimachinery/pkg/util/net
vendor/k8s.io/apimachinery/pkg/util/net/http.go:293: req.URL.Hostname undefined (type *url.URL has no field or method Hostname)

**Comment by floryut** [comment]
No more relevant with change to go mod
