### ISSUE TITLE
Support filtering by the node name

### ISSUE THREAD

**Issue by tksm** [stern/stern#242]
**What would you like to be added**:

I would like to add a flag `--node` that filters pods by the node name. This flag will be helpful when we debug pods on the specific node.

```
# Print a DaemonSet pod on the specific node
stern --node <NODE_NAME> daemonsets/<DS_NAME>

# Print all pods on the specific node
stern --node <NODE_NAME> --no-follow --max-log-requests 1 .
```

**Why is this needed**:

We can select pods on the specific node by `--field-selector spec.nodeName=<NODE_NAME>` too, but having a dedicated flag allows us to implement a completion for node names.

**Comment by superbrothers** [comment]
> We can select pods on the specific node by --field-selector spec.nodeName=<NODE_NAME> too, but having a dedicated flag allows us to implement a completion for node names.

+1
