### ISSUE TITLE
stern template parseJson failed to output properties with special characters

### ISSUE THREAD

**Issue by superwalnut** [stern/stern#245]
**What happened**:

I have a kube log in json format, it has property like "@t", i.e. the timestamp. stern successfully parsed the json and I have no way to retrieve the property in the template.

I tried to do '{{with $d := .Message | parseJSON}}[{{$d.@t}}][{{$d.LogLevel}}]' , it failed and complains about the @ sign. Could you fix this? Thank you

**What you expected to happen**:
To allow stern template retrieve json properties with special characters.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- stern version (use `stern --version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools (e.g: Homebrew)
- Others:

**Comment by superbrothers** [comment]
You need to use `index` function for special characters.

```
stern --template '{{with $d := .Message | parseJSON}}{{ index $d "@t" }}{{end}}{{"\n"}}' .
```

- https://discourse.gohugo.io/t/template-error-bad-character-u-0024/26885/2

I'll close this issue. If you still have any issues, please feel free to reopen it.
