### ISSUE TITLE
Allow to use stern as a kubectl plugin

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#25]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/102, but it was originally created by [kivagant-ba](https://github.com/kivagant-ba)...

Please, make `stern` available as a plugin for `kubectl` to use it as `kubectl stern ...`.

In additional, make it searchable by [`kubectl krew search`](https://github.com/GoogleContainerTools/krew).

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [jan25](https://github.com/jan25)...

This'd be nice!

Firstly we'll need to edit the latest release tag to attach the executables wrapped in `.zip` or `.tar.gz` compressed files. Would someone be able to help with that? @walterbot 

After that we can continue to open a PR to `krew-index` with preliminary changes i have here https://github.com/kubernetes-sigs/krew-index/compare/master...jan25:add-stern?expand=1#diff-694169189386283d3ec578d120d24581

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [Luffy110](https://github.com/Luffy110)...

Hi i think this is a great thing to do ! because the stern has a greater user experience than kail. why nobody push this ? 

I found a way , we can do it by self. we can download the binary file then rename it to kubectl-stern, and move it to home/.krew/bin/. then you can use kubectl stern .

**Comment by paulolieuthier** [comment]
That would be nice.

**Comment by tuananh** [comment]
i prefer stern over kail because of the much better user exp. this would be a welcome addition

**Comment by superbrothers** [comment]
I added stern to the krew index, so now you can install stern via Krew!

```
kubectl krew install stern
```

- https://github.com/kubernetes-sigs/krew-index/pull/1805
