### ISSUE TITLE
stern seems to be incompatible with GCP Kubernetes auth

### ISSUE THREAD

**Issue by twocs** [stern/stern#268]
**What happened**:

Now that Google has changed authentication, I'm no longer able to use stern with Gcloud.
`Error: The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details`

**What you expected to happen**:

The authentication is set up fine on my computer, so kubectl works as expected. I would assume that stern would just pick up all needed config from kubectl and work as expected. 

**How to reproduce it (as minimally and precisely as possible)**:
Try to use stern with kubectl that is set up to access gcloud.

**Anything else we need to know?**:

I'm not clear on what I would need to do to get this working. Possibly it requires a new import of the gke-gcloud-auth-plugin in stern.

**Environment**:
- stern version (use `stern --version`): version: 1.25.0
- OS (e.g: `cat /etc/os-release`):
`❯ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a`
- Install tools (e.g: Homebrew): homebrew
- Others:
I have the plugin installed.
```zsh
❯ gcloud components install gke-gcloud-auth-plugin
All components are up to date.
❯ gcloud components update
Beginning update. This process may take several minutes.
All components are up to date.
```

**Comment by tksm** [comment]
Hi,

Stern should work with GKE clusters because GKE uses the [client-go credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) mechanism. I have tested stern v1.25.0 with gke-gcloud-auth-plugin 0.5.3 on my GKE cluster, and it worked successfully.

Could you please try running [`gcloud container clusters get-credential`](https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials) to see if it fixes the issue? Your kubeconfig might not have been updated after installing the plugin.

```
gcloud container clusters get-credentials <CLUSTER> --region <REGION> --project <PROJECT>
```

**Comment by twocs** [comment]
I checked `~/.kube/config` and the settings seemed to be correct.
I ran `gcloud container clusters get-credentials <CLUSTER>`. It seems to have done a refresh.
```zsh
❯ gcloud container clusters get-credentials apod-api                  
Fetching cluster endpoint and auth data.
kubeconfig entry generated for apod-api.
```
Now `stern` is working.

**Comment by tksm** [comment]
I'm glad the issue has been resolved :tada:

I believe that your old kubeconfig was likely using the deprecated `gcp` auth-provider as follows. The `gcp` auth-provider was removed in client-go 1.26.

```yaml
- name: gke_api-project-xxxx
  user:
    auth-provider:
      name: gcp # removed in client-go 1.26
```

I think your new kubeconfig now correctly uses the new plugin mechanism `exec`.

```yaml
- name: gke_api-project-xxxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      # ...
```
