### ISSUE TITLE
Chinese garbled code（中文乱码问题）

### ISSUE THREAD

**Issue by sky508** [stern/stern#272]
**What happened**:
Hello, garbled characters are found in logs, but the Chinese characters of the server and container are not garbled。（你好，在查看日志时发现中文乱码，但是服务器和容器本身中文是不乱码的）
**What you expected to happen**:
![image](https://github.com/stern/stern/assets/26371416/4b6bcfa1-1351-4676-b880-622930f83b09)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- stern version (use `stern --version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools (e.g: Homebrew)
- Others:

**Comment by tksm** [comment]
Hi,
What is the output when you see the logs with `kubectl logs`?

**Comment by tksm** [comment]
I don't think it is Stern's bug. Based on the garbled characters, they appear to be incorrectly encoded as [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252), but Stern does not handle character encoding. The issue may be a result of your application or terminal incorrectly encoding characters.

Please reopen the issue if you find any differences between stern and kubectl logs.
