### ISSUE TITLE
doesn't work with install of microk8s

### ISSUE THREAD

**Issue by DraconPern** [stern/stern#284]
**What happened**:
Getting the error: "Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"

**What you expected to happen**:
print out logs for deployment

**How to reproduce it (as minimally and precisely as possible)**:
Install microk8s on ubuntu 22.  Run stern on any deployment

**Anything else we need to know?**:

**Environment**:
- stern version (use `stern --version`):
version: 1.26.0
commit: 26839e4d610acec6e21020c879688ec96b1608da
built at: 2023-08-21T02:34:50Z

- OS (e.g: `cat /etc/os-release`):
Ubuntu 22.04

- Install tools (e.g: Homebrew)
downloaded as tarball
- Others:

**Comment by tksm** [comment]
Hi,

Do you have the [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) file at `$HOME/.kube/config`? Stern needs the kubeconfig to access clusters, just like kubectl.

**Comment by DraconPern** [comment]
Can confirm that I don't have a kubeconfig file at that location.  However, microk8s kubectl doesn't seen to need it to access it.  Had to manually generate one, then stern works.  I suppose then a feature request is to locate whatever microk8s kubectl uses for config...

**Comment by tksm** [comment]
I found kubectl has the default server (`http://localhost:8080`) if the kubeconfig does not exist, unlike stern v1.26.0. This might explain why kubectl can access your cluster without a kubeconfig.

Stern on master (f315819) already has this behavior, so it will be resolved in the next release.

**Comment by superbrothers** [comment]
OK. We will release it. I will prepare.

**Comment by superbrothers** [comment]
I have now released v1.27.0. Please try it out.

**Comment by jan-osch** [comment]
I have the same issue but with k8s in Docker for Mac

```
k get pods
NAME           READY   STATUS    RESTARTS   AGE
runner-9zxdm   1/1     Running   0          4m18s
runner-chs2n   1/1     Running   0          4m18s
runner-j55f2   1/1     Running   0          4m18s
runner-pgmb4   1/1     Running   0          2m14s
runner-t9zt4   1/1     Running   0          4m18s
```

But `stern * -A` shows nothing. `$HOME/.kube/config` exists

**Comment by superbrothers** [comment]
Could you try the following command? 

```
# stern <pod-query>
stern . -A
```

pod-query is regular expression, not glob. This is probably due to the fact that it doesn't match anything in `*`
