### ISSUE TITLE
`-t default` seems broken: no output

### ISSUE THREAD

**Issue by guettli** [stern/stern#294]
**What happened**:

```
❯ stern  --since=2m --no-follow --only-log-lines -n kube-system -t default .
--> no output.
```

**What you expected to happen**:

I would like to see output. If I remove `-t default`, I see output:

```
❯ stern  --since=2m --no-follow --only-log-lines -n kube-system . | head    
ccm-7f8b59bc4d-zsbv4 ccm I0423 11:32:37.329272    ...
```

**How to reproduce it (as minimally and precisely as possible)**:

Use `-t default`

**Anything else we need to know?**:

**Environment**:
- stern version (use `stern --version`): version: 1.28.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.4 LTS
- Install tools (e.g: Homebrew) via brew
- Others: Used directly, not via kubectl

**Comment by tksm** [comment]
Hi, thanks for reporting.

I forgot to write that `=` cannot be omitted in `--timestamps=short`, as the flag has [a no option default value](https://github.com/spf13/pflag?tab=readme-ov-file#setting-no-option-default-values-for-flags). I will update the README to clarify this behavior.

**Comment by guettli** [comment]
> Hi, thanks for reporting.
> 
> I forgot to write that `=` cannot be omitted in `--timestamps=short`, as the flag has [a no option default value](https://github.com/spf13/pflag?tab=readme-ov-file#setting-no-option-default-values-for-flags). I will update the README to clarify this behavior.

I have concerns that people don't read the README. Maybe it is better to remove the option default?

**Comment by tksm** [comment]
> I have concerns that people don't read the README.

Thank you for pointing out. I am thinking of also updating the help of the --timestamps flag as follows.

>   -t, --timestamps string[="default"]   Print timestamps with the specified format. One of 'default' or 'short' in the form '--timestamp=format' ('=' cannot be omitted). If specified but without value, 'default' is used.

**Comment by guettli** [comment]
Yes, this looks good. Thank you!
