### ISSUE TITLE
I was thinking of adding a flag for container index?

### ISSUE THREAD

**Issue by Aracki** [stern/stern#309]
Whenever I have several containers within a pod all share the same prefix name. Then, when I want to print the logs of only the first container I need to use `-E 'container_1 | container_2 | container_3`. 

Do you think it would make sense for stern to have a flag like `--container-index=0` to print the logs of only the first container within a pod?

**Comment by superbrothers** [comment]
> Then, when I want to print the logs of only the first container I need to use -E 'container_1 | container_2 | container_3.

In your example, would the container name at index 0 be "container"? If so, you can do the following.

```
stern app -c '^container$'
```
