### ISSUE TITLE
Show all logs from all containers from all states together including previous containers

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#36]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/117, but it was originally created by [kivagant-ba](https://github.com/kivagant-ba)...

Related to:
- https://github.com/wercker/stern/issues/72
- https://github.com/wercker/stern/issues/103
- https://github.com/wercker/stern/issues/68

Stern is very useful and great but there are some cases where it requires additional commands.
It would be nice to have the only one option to print-and-exit _everything_ that matches the given filter:

- logs from active pods and all their containers inside.
- logs from terminated/exited pods (completed jobs) and all their containers.
- logs from all previous containers that crashed/exited and restarted by Kubernetes.
- everything else that Stern can support.

So the feature request combines other issues together to get all available logs without using any parameters combinations.

Use case:
1. Install a Helm chart without analyzing its resources.
2. With `stern` print logs from everything installed based on the project name including jobs, crashed pods, running pods etc.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [rmetzler](https://github.com/rmetzler)...

I would love to see logs from completed pods. That way I could stern to view logs from cronjobs.

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [hulucc](https://github.com/hulucc)...

And it's useful when debugging problems

**Comment by superbrothers** [comment]
**Note:** this comment was imported, but it was originally made by [brettplarson](https://github.com/brettplarson)...

This would be great!

**Comment by DTTerastar** [comment]
Not showing terminated pods JUST bit me when demoing stern.  It should not default that way.  The most common case for looking for logs to figure out why it started and immediately died!

**Comment by igortavtib** [comment]
I think this issue was solved by https://github.com/stern/stern/pull/222
