### ISSUE TITLE
Suggestion Time in Custom Format

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#43]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/125, but it was originally created by [derekrprice](https://github.com/derekrprice)...

I'd like to be able to add a short timestamp (no decimal seconds) in a custom format string.  My use case is mostly making the log lines fit better on my monitor.

**Comment by tyrken** [comment]
Not sure if possible with a custom format, but the option to display `--timestamps` with local timezone would be really useful to avoid the continual mental leap from UTC to "now"

**Comment by superbrothers** [comment]
`--timestamps` option uses the functionality of `kubectl logs --timestamps`, so it cannot be changed in a custom template. Also, probably `kubectl logs` cannot change timezone either, so we will consider our own implementation in stern.

**Comment by superbrothers** [comment]
@floryut I'm thinking of using the local timezone by default when the `--timestamps` option is used, and specifying it in `TZ` environment variable if you want to change the timezone. This is a breaking change, but I think it will be easier to use. What do you think?

**Comment by floryut** [comment]
> @floryut I'm thinking of using the local timezone by default when the `--timestamps` option is used, and specifying it in `TZ` environment variable if you want to change the timezone. This is a breaking change, but I think it will be easier to use. What do you think?

That would totally make sense 👍
