### ISSUE TITLE
Stern bash completions clash with kubectl completions

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#50]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/137, but it was originally created by [drzero42](https://github.com/drzero42)...

I just spent some time troubleshooting a weird problem I was experiencing with kubectl on my system. I noticed that recently I could not get kubectl to autocomplete names of deployments, statefulsets, replicasets and pods. It would gladly autocomplete namespaces, crds, storageclasses, secrets, configmaps and others. As most of my cluster don't have anything in the default namespace, but rather put everything into other namespaces, at first I thought name completion was totally broken, but it turned out that it was just looking in the default namespace, even though I was trying to tab-complete the name of a pod in a different namespace, eg: `kubectl -n kube-system describe pod <tab><tab>`.

I load bash completions from my .bashrc with `source <(kubectl completion bash)`. I also load completions for a bunch of other commands, like minikube, kind, argocd and also stern. I decided to try loading the kubectl completions by hand in my terminal, which made it work. So I went to my .bashrc and started experimenting with the order that I loaded the completions in, and quickly discovered that if stern completions are loaded after kubectl completions, then I can't autocomplete names from any other namespace than default.

I am in no way an expert on how to write bash completion functions, but a quick look at the output of `stern --completion bash` and comparing to the output of `kubectl completion bash`, I see stern defining a number of functions that kubectl also defines. Thus, if the stern bash completions are loaded after the kubectl completions, it screws them up. It would be great if the stern bash completions could work without fiddling with kubectl completions ;)

**Comment by ilovekate19** [comment]
I have the same issue. is it fixed ? if yes, would you pleaset let me know which version has the fix.

**Comment by superbrothers** [comment]
It has been fixed on v1.12.0 and later.

**Comment by ilovekate19** [comment]
Thanks for your quick reply!
