### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#59]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/146, but it was originally created by [larytet](https://github.com/larytet)...

build std/github.com/wercker/stern: cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2

**Comment by floryut** [comment]
No more relevant with new build method.
