### ISSUE TITLE
Remove support for --all-namespaces and add support for multiple --namespace

### ISSUE THREAD

**Issue by ssoriche** [stern/stern#73]
I work with several large clusters with a lot of namespaces. Running stern and specifying `--all-namespaces` is potentially costly and dangerous to the health of the cluster. I would like to remove the option to specify `--all-namespaces`, and replace it with the ability to specify multiple `--namespace` options. The thinking is that there is more thought required to adding each namespace than just asking for every one.

**Comment by floryut** [comment]
Well I agree that specifying namespace could be an added option but I'm strongly against removing all namespaces as it's pretty much my daily use case :)

**Comment by superbrothers** [comment]
I've probably never used `--all-namespaces` before. I don't know the case where I want to log across all namespaces.

On the other hand, in an environment with thousands or tens of thousands of pods, it's true that execution with the `--all-namespaces` flag is dangerous.

**Comment by floryut** [comment]
I have some use cases with resources handle by operator on our end, which create some pods in each namespace declared by users.
And sometime I want to check all those pods, I only know the name not the namespace (well I can get it of course with a `k get pod -A`) and it's very handy to be able to follow all those pods without doing anything.

Also I'm lazy and sometime I want to check api pods without having to specify `n kube-system` and only doing `-A`  :P

I'm really strongly against removing it (or even drepracating it).
But I agree that we could support multiple namespace and maybe put a warning on `all-namespace` so people understand the "risk"

**Comment by superbrothers** [comment]
> And sometime I want to check all those pods, I only know the name not the namespace (well I can get it of course with a k get pod -A) and it's very handy to be able to follow all those pods without doing anything.

I understand your use case. For now, leave it as it is until more similar opinions come. :+1:

**Comment by ssoriche** [comment]
I understand the use case on smaller clusters, I have one of those myself that it is just easier to use `-A` on to see what's going on, but the environment I really care about and have other users that could really benefit using stern on has a thousand namespaces and tens of thousands of pods. It wouldn't take much for an accidental `--all-namespaces` in there and do some damage.

A warning message only helps if the user can stop the process before it communicates with the API. What about a configuration option that enables the use of `--all-namespaces`?

**Comment by superbrothers** [comment]
@ssoriche @floryut How about setting an upper limit on the number of pods or containers to handle? When the limit is reached, stern is terminated. This also makes the `--all-namespaces` flag safe.

What do you think about setting the maximum number of pods to 100?

**Comment by floryut** [comment]
> @ssoriche @floryut How about setting an upper limit on the number of pods or containers to handle? When the limit is reached, stern is terminated. This also makes the `--all-namespaces` flag safe.
> 
> What do you think about setting the maximum number of pods to 100?

That'd way more than enough 👍

**Comment by ssoriche** [comment]
> @ssoriche @floryut How about setting an upper limit on the number of pods or containers to handle? When the limit is reached, stern is terminated. This also makes the --all-namespaces flag safe.

> What do you think about setting the maximum number of pods to 100?

This is a great idea. I think that the number of pods/containers needs to be checked prior to initiating the log stream, and that the limit should be what would be reasonable for a person to view at one time. I can't imagine someone comfortably viewing 100 logs concurrently.

I also had a thought to allow namespace pattern matching, with the same (maybe smaller) limit on pods/containers.

**Comment by mailsanchu** [comment]
I like this feature to get logs from multiple namespaces but the logs should clearly indicate the logs are from which namespace.Otherwise it will cause confusion

**Comment by superbrothers** [comment]
> I like this feature to get logs from multiple namespaces but the logs should clearly indicate the logs are from which namespace.Otherwise it will cause confusion

If `--all-namespaces` option is enabled, a namespace name is given to the output as follows:

```
$ stern --all-namespaces kube-apiserver
kube-system kube-apiserver-kind-control-plane kube-apiserver Trace[133858303]: ---"Transformed response object" 3752ms (14:14:00.120)
```

We will need to do the same when supporting multiple namespaces.

**Comment by superbrothers** [comment]
`kubectl logs` command already has such an option. Also, the maximum number of log streams is set to 5 by default.

```
$ kubectl logs --help | grep -- --max-log-requests
      --max-log-requests=5: Specify maximum number of concurrent logs to follow when using by a selector. Defaults to 5.
```

However, I feel that 5 is a few for stern.

**Comment by floryut** [comment]
Yes hard to set a number but something like 10/20 is still manageable (when someone know what is he doing)
